services:
  devcontainer:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKSPACES=${WORKSPACES}
        - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    init: true
    volumes:
      - WORKSPACES:${WORKSPACES}
      - ..:${WORKSPACES}/${COMPOSE_PROJECT_NAME}
      - XDG_CONFIG_HOME:${XDG_CONFIG_HOME}
      - XDG_CACHE_HOME:${XDG_CACHE_HOME}
      - XDG_DATA_HOME:${XDG_DATA_HOME}
      - XDG_STATE_HOME:${XDG_STATE_HOME}
      - node_modules:${WORKSPACES}/${COMPOSE_PROJECT_NAME}/node_modules
      - node_modules:${WORKSPACES}/node_modules
volumes:
  WORKSPACES:
  XDG_CONFIG_HOME:
  XDG_CACHE_HOME:
  XDG_DATA_HOME:
  XDG_STATE_HOME:
  node_modules:
